export const BOOK_GENRES = [
  "Action",
  "Adventure",
  "Anthology",
  "Art",
  "Autobiography",
  "Biography",
  "Business",
  "Children",
  "Classic",
  "Comedy",
  "Contemporary",
  "Cookbook",
  "Crime",
  "Cyberpunk",
  "Dark Fantasy",
  "Dystopian",
  "Education",
  "Epic Fantasy",
  "Erotica",
  "Essay",
  "Fairy Tale",
  "Fantasy",
  "Graphic Novel",
  "Historical",
  "Historical Fiction",
  "History",
  "Horror",
  "Humor",
  "Literary Fiction",
  "Manga",
  "Memoir",
  "Military Fiction",
  "Mystery",
  "Mythology",
  "New Adult",
  "Nonfiction",
  "Paranormal",
  "Philosophy",
  "Poetry",
  "Political",
  "Psychology",
  "Religion",
  "Romance",
  "Satire",
  "Science",
  "Science Fiction",
  "Self-Help",
  "Short Stories",
  "Spirituality",
  "Sports",
  "Steampunk",
  "Suspense",
  "Technology",
  "Thriller",
  "Travel",
  "True Crime",
  "Urban Fantasy",
  "War",
  "Western",
  "Women's Fiction",
  "Young Adult",
] as const
